server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true
