server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

spring.cloud.config.discovery.enabled: true
