server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

spring.cloud.config.discovery.enabled: true