server:
  port: 8888

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xdpsee/springcloud-study.git
          searchPaths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

